allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  sharp: set this to true or false
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@nuxt/icon@2.4.1'
